// Generated by scripts/generate-migrations.mjs — do not edit.
// Run "pnpm db:generate" (or this script) after "drizzle-kit generate".

export interface BundledMigration {
  name: string
  sql: string
}

export const migrations: BundledMigration[] = [
  {
    name: '20260903130543_nebulous_swarm',
    sql: 'CREATE TABLE IF NOT EXISTS `lists` (\n\t`id` text PRIMARY KEY,\n\t`name` text NOT NULL,\n\t`color` text NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE IF NOT EXISTS `tasks` (\n\t`id` text PRIMARY KEY,\n\t`listId` text NOT NULL,\n\t`title` text NOT NULL,\n\t`notes` text NOT NULL,\n\t`done` integer DEFAULT false NOT NULL,\n\t`important` integer DEFAULT false NOT NULL,\n\t`deleted` integer DEFAULT false NOT NULL,\n\t`due` text,\n\t`position` integer DEFAULT 0 NOT NULL,\n\t`createdAt` text NOT NULL,\n\t`completedAt` text\n);\n'
  },
  {
    name: '20260905151621_powerful_blade',
    sql: 'CREATE TABLE `contacts` (\n\t`id` text PRIMARY KEY,\n\t`name` text NOT NULL,\n\t`firstName` text\n);\n'
  },
  {
    name: '20260905151910_huge_star_brand',
    sql: 'ALTER TABLE `contacts` ADD `companyId` text REFERENCES contacts(id);'
  }
]
